import Disc from './components/newUserStack/Disclaimer';
import Log from './components/newUserStack/LoginForm';
import Wel from './components/newUserStack/Welcome';
import Zip from './components/newUserStack/zipConfirm';
import mainTit from './components/returningUserStack/MainTitles';
import HomeScr from './components/returningUserStack/HomeScreen';
import Currentbee from './components/returningUserStack/CurrentBeers';
import YourCrate from './components/returningUserStack/YourCrates';
import Subscrib from './components/returningUserStack/Subscribe';
import MyBee from './components/returningUserStack/MyBeers';
import CreateAcc from './components/newUserStack/createAccnt';
import NewUserStart from './components/newUserStack/NewUserStartPage';
import ReturnUser from './components/returningUserStack/ReturningUser';

export const ReturningUserStack = ReturnUser;
export const NewUserStartStack = NewUserStart;
export const CreateAccnt = CreateAcc;
export const MyBeers = MyBee;
export const Subscribe = Subscrib;
export const YourCrates = YourCrate;
export const CurrentBeers = Currentbee;
export const HomeScreen = HomeScr;
export const MainTitle = mainTit;
export const ZipConfirm = Zip;
export const Disclaimer = Disc;
export const LoginForm = Log;
export const Welcome = Wel;
